# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Implementing FHIR'
tagline:          'An adventure in Rust and obsessive spec reading'
url:              http://arienmalec.github.io
paginate:         3
baseurl:          /implementing-fhir
author:
  name:           Arien Malec
  url:            https://twitter.com/amalec

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/arienmalec/implementing-fhir
