# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Implementing FHIR'
tagline:          'An adventure in Rust and obsessive spec reading'
url:              http://arienmalec.github.io/implementing-fhir/
paginate:         1
baseurl:          ""
author:
  name:           Arien Malec
  url:            https://twitter.com/amalec

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
